[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20190103044641-3857bee/master-haskell-20190103044641-3857bee"
  version = 1
  sha1 = "c8396097bdf46fa16aae6660f8d1f3ea7a4bce72"

[global]
  CACHE = "true"

#[build.dist-8-2]
#  GHC_VERSION = "8.2.2"
#  CABAL_VERSION = "2.0.0.1"
#
#[build.branches-8-2]
#  GHC_VERSION = "8.2.2"
#  CABAL_VERSION = "2.0.0.1"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"

[build.dist-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"

[build.branches-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
